name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: volta-cli/action@v4
      - uses: pnpm/action-setup@v4

      - run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm -F vite-plugin-style publish --no-git-checks

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./packages/vite-plugin-style/CHANGELOG.md
